# This is a basic workflow to help you get started with Actions

name: Java CI

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'docs/**'
      - '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
          cache: maven
      - name: Install dependencies
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: Run tests and collect coverage
        run: mvn -B test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: codecov-umbrella
          token: ${{secrets.CODECOV_TOKEN}}
